version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/app
    steps:
      - checkout
      - run: npm run lint
      - run: npm run test-unit

  publish_package:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm build
          command: npm run build
      - run:
          name: npm publish
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            npm publish
      - run:
          name: publish gh pages
          command: ./tools/deploy-gh-pages.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - publish_package:
          requires:
            - test
          filters:
            branches:
              only:
                - master
