version: 2
jobs:
  check_branch_name:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/app
    steps:
      - checkout
      - run: env
      - run:
          name: fail if the branch name does not start with a valid prefix
          command: |
            branch=$CIRCLE_BRANCH
            if [[ "$branch" =~ ^(fix|feature|breaking)/ ]]
            then
              echo $branch is a valid name
            else
              echo $branch is not valid because the branch name must match '^(fix|feature|breaking)/'
              exit 1
            fi
  deploy_test_environment:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: publish gh pages for a test environment
          command: ./tools/deploy-gh-pages-pr.sh
  test:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn install --non-interactive
      - run: yarn lint
      - run: yarn test:unit
      - run: yarn build
  test-e2e:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Running E2E tests
          command: docker-compose -f ./docker-compose.e2e.yml up --build --exit-code-from e2e-test

  publish_package:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: yarn install --non-interactive
      - run:
          name: npm publish CDN version
          command: |
            sed -i 's/export default Carousel;/global.BrainhubeuReactCarousel = Carousel; export default Carousel;/g' src/components/Carousel.js
            sed -i 's/export default CarouselDots;/global.BrainhubeuReactCarouselDots = CarouselDots; export default CarouselDots;/g' src/components/CarouselDots.js
            sed -i 's/export default CarouselItem;/global.BrainhubeuReactCarouselItem = CarouselItem; export default CarouselItem;/g' src/components/CarouselItem.js
            sed -i 's/export default CarouselWrapper;/global.BrainhubeuReactCarouselWrapper = CarouselWrapper; export default CarouselWrapper;/g' src/components/CarouselWrapper.js
            yarn build
            sed -i 's/  "version": "\(.*\)",/  "version": "\1-cdn",/g' package.json
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            npm publish
            git config --global user.email "devops@brainhub.pl"
            git config --global user.name "DevOps Brainhub"
            git add .
            git stash
      - run:
          name: npm publish
          command: |
            yarn build
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            npm publish
      - run:
          name: publish gh pages
          command: ./tools/deploy-gh-pages.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - check_branch_name
      - test:
          requires:
            - check_branch_name
      - test-e2e:
          requires:
            - check_branch_name
      - deploy_test_environment:
          requires:
            - check_branch_name
      - publish_package:
          requires:
            - test
            - test-e2e
            - deploy_test_environment
          filters:
            branches:
              only:
                - master
